name: Pull Request Reviewed

on:
  pull_request_review:
    types: [submitted]

jobs:
  administration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: PR labeling
        uses: srvaroa/labeler@v1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
